----------------- 
<class 'FileNotFoundError'>FileNotFoundError(2, 'No such file or directory')Traceback (most recent call last):
  File "/Users/yves/Documents/Code/pyhomecage/GUI.py", line 194, in <module>
    gui = Visualizator()
  File "/Users/yves/Documents/Code/pyhomecage/GUI.py", line 90, in __init__
    self.protocol_tab = scheduler(self)
  File "/Users/yves/Documents/Code/pyhomecage/schedule_manager.py", line 57, in __init__
    self.available_tasks = get_tasks(self.GUI.GUI_filepath)
  File "/Users/yves/Documents/Code/pyhomecage/utils.py", line 156, in get_tasks
    tasks =  [t.split('.')[0] for t in os.listdir(task_dir) if t[-3:] == '.py']
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yves/Documents/Code/pyhomecage/tasks'
2022-02-10-122305
----------------- 
<class 'IndexError'>IndexError('list index out of range')Traceback (most recent call last):
  File "/Users/yves/Documents/Code/pyhomecage/dialogs.py", line 389, in send_code
    sender_email,password = get_pyhomecage_email()
  File "/Users/yves/Documents/Code/pyhomecage/utils.py", line 71, in get_pyhomecage_email
    sender_email =  re.findall('"(.*)"',[l_ for l_ in lines_ if 'system_email' in l_][0])[0]
IndexError: list index out of range
2022-02-10-122337
----------------- 
<class 'KeyboardInterrupt'>KeyboardInterrupt()Traceback (most recent call last):
  File "/Users/yves/Documents/Code/pyhomecage/GUI.py", line 130, in refresh
    def refresh(self):
KeyboardInterrupt
2022-02-10-123039
----------------- 
<class 'TypeError'>TypeError("__init__() got an unexpected keyword argument 'GUI'")Traceback (most recent call last):
  File "/Users/yves/opt/anaconda3/envs/pycontrol_homecage/bin/GUI.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/GUI.py", line 169, in <module>
    gui = Visualizator()
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/GUI.py", line 54, in __init__
    self._init_tabs()
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/GUI.py", line 76, in _init_tabs
    self.system_tab = system_tab(self)
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/system_overview.py", line 50, in __init__
    self.list_of_experiments = experiment_overview_table(GUI=self.GUI, only_active=True)
TypeError: __init__() got an unexpected keyword argument 'GUI'
2022-04-06-111853
----------------- 
<class 'AttributeError'>AttributeError("'Visualizator' object has no attribute 'controllers'")Traceback (most recent call last):
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/setup_view_tab.py", line 113, in cbh
    if len(self.GUI.controllers)==0:
AttributeError: 'Visualizator' object has no attribute 'controllers'
2022-04-06-111956
----------------- 
<class 'AttributeError'>AttributeError("'Visualizator' object has no attribute 'controllers'")Traceback (most recent call last):
  File "/Users/yves/Documents/Code/pyhomecage/src/pycontrol_homecage/setup_view_tab.py", line 140, in update_setup
    if len(self.GUI.controllers)==0:
AttributeError: 'Visualizator' object has no attribute 'controllers'
2022-04-06-111957
